### ISSUE TITLE
Better implementation for Multi-Delete

### ISSUE THREAD

**Issue by asgrim** [Roave/DoctrineSimpleCache#2]
Following on from discussion: https://github.com/Roave/DoctrineSimpleCache/pull/1#discussion_r94380168

Doctrine will soon support an interface for multi-delete apparently, so we can simplify and tidy up our implementation.

**Comment by asgrim** [comment]
Depends on doctrine/cache#186

**Comment by asgrim** [comment]
Oh wait, it got merged in doctrine/cache#155

**Comment by asgrim** [comment]
So we just need to wait for tagging (current version is `1.6.1` but because it's a new feature, I'd expect it to be available in `1.7.0`)

**Comment by lcobucci** [comment]
@asgrim `v1.7.0` has been released https://github.com/doctrine/cache/releases/tag/v1.7.0 😉

**Comment by asgrim** [comment]
Nice! We'll look into this, cheers @lcobucci :)
