### ISSUE TITLE
support for PHP 7.2+ is missing

### ISSUE THREAD

**Issue by mimmi20** [Roave/DoctrineSimpleCache#23]
Actually this project is not installable with PHP 7.2+. Please add support for these upsomming PHP version.

**Comment by Ocramius** [comment]
@mimmi20 can you send a patch that adds testing for it?

We are very vary of supporting next PHP versions upfront, since PHP is not really SemVer compliant

**Comment by asgrim** [comment]
@mimmi20 & @Ocramius PR is already open in #21 but blocked due to no xdebug support at the time, I haven't checked if that still holds true though, so might be worth checking.

**Comment by mimmi20** [comment]
@asgrim any news?

**Comment by Ocramius** [comment]
@mimmi20 re-running builds atm

**Comment by asgrim** [comment]
PR #21 updated, sorry for the delay

**Comment by asgrim** [comment]
Closed with #21
