### ISSUE TITLE
Incorrect exception thrown when ClearableCache not used

### ISSUE THREAD

**Issue by joshbrw** [Roave/DoctrineSimpleCache#25]
https://github.com/Roave/DoctrineSimpleCache/blob/2.1.0/src/SimpleCacheAdapter.php#L28

Should this line not be:

```
throw Exception\CacheException::fromNonClearableCache($this->doctrineCache);
```

Rather than

```
throw Exception\CacheException::fromNonMultiOperationCache($this->doctrineCache);
```

**Comment by asgrim** [comment]
Ah that is indeed a good shout... to fix this means technically a BC break, but as the release is not too old, I think we could probably patch this quickly, WDYT @Ocramius ?

**Comment by Ocramius** [comment]
@asgrim if we are following the interface definition, this is not a BC break.

**Comment by Ocramius** [comment]
Anyway, the same exception is raised, so nothing changes on the consumer.

**Comment by asgrim** [comment]
OK thanks :+1: I'll get this fixed then today

**Comment by joshbrw** [comment]
Awesome - thanks @asgrim!
