### ISSUE TITLE
[Suggestion] Run tests against the shared integration testsuite

### ISSUE THREAD

**Issue by stof** [Roave/DoctrineSimpleCache#8]
https://github.com/php-cache/integration-tests maintains a set of integration tests for PSR cache implementations. As of 0.14.0, it supports PSR-16 too rather than only PSR-6 (the readme does not showcase it, but I opened a PR updating it at https://github.com/php-cache/integration-tests/pull/68

It would be great to run tests against it too (without mocking doctrine/cache), to ensure that it behaves properly according to the spec.

**Comment by stof** [comment]
Btw, your 1.0 implementation does not respect the spec regarding exceptions...

**Comment by asgrim** [comment]
Tests are added in #12, but we are currently skipping those that fail. This is a bug until resolved therefore.

**Comment by asgrim** [comment]
Partially implemented in #13 (for TTL) which is now merged, and #15 which is pending resolution of issue discovered in integration test (see: php-cache/integration-tests#74 )

**Comment by asgrim** [comment]
* ~~`testSetTtl`~~ #13
 * ~~`testSetExpiredTtl`~~ #13
 * ~~`testSetMultipleTtl`~~ #13
 * ~~`testSetMultipleExpiredTtl`~~ #13
 * `testSetMultipleWithGenerator` **todo**
 * `testGetMultipleWithGenerator` **todo**
 * `testGetInvalidKeys` #15
 * `testGetMultipleInvalidKeys` #15
 * `testGetMultipleNoIterable` **todo**
 * `testSetInvalidKeys` #15
 * `testSetMultipleInvalidKeys` #15
 * `testSetMultipleNoIterable` **todo**
 * `testHasInvalidKeys` #15
 * `testDeleteInvalidKeys` #15
 * `testDeleteMultipleInvalidKeys` #15
 * `testDeleteMultipleNoIterable` **todo**
 * ~~`testSetInvalidTtl`~~ #13
 * ~~`testSetMultipleInvalidTtl`~~ #13
 * `testObjectDoesNotChangeInCache` **todo**
 * `testDataTypeBoolean` #17

**Comment by asgrim** [comment]
Opened issue #20 for `testObjectDoesNotChangeInCache`.

**Comment by asgrim** [comment]
Otherwise, closed by various PRs listed above.
